upstreams:
  groups:
    default:
      - tcp-tls:8.8.4.4
      - https://8.8.4.4/dns-query
      - tcp-tls:8.8.8.8
      - https://8.8.8.8/dns-query
      - tcp-tls:dns.google
      - https://dns.google/dns-query
      - tcp-tls:9.9.9.10
      - https://9.9.9.10/dns-query
      - https://dns10.quad9.net/dns-query
      - tcp-tls:1.1.1.1
      - https://1.1.1.1/dns-query
      - tcp-tls:1.0.0.1
      - https://1.0.0.1/dns-query
      - https://cloudflare-dns.com/dns-query
      - https://mozilla.cloudflare-dns.com/dns-query
      - tcp-tls:dns.nextdns.io
      - https://dns.nextdns.io
      - tcp-tls:anycast.dns.nextdns.io
      - https://anycast.dns.nextdns.io
      - https://firefox.dns.nextdns.io
      - tcp-tls:open.dns0.eu
      - https://open.dns0.eu/dns-query
      - tcp-tls:dns0.eu
      - https://dns0.eu/dns-query
      - tcp-tls:p0.freedns.controld.com
      - https://freedns.controld.com/p0
      - tcp-tls:uncensored.freedns.controld.com
      - https://freedns.controld.com/uncensored
      - tcp-tls:private.canadianshield.cira.ca
      - https://private.canadianshield.cira.ca/dns-query
      - tcp-tls:safeservedns.com
      - https://safeservedns.com/dns-query
      - tcp-tls:max.rethinkdns.com
      - https://max.rethinkdns.com
      - tcp-tls:uncensored.dns.dnswarden.com
      - https://dns.dnswarden.com/uncensored
      - tcp-tls:wikimedia-dns.org
      - https://wikimedia-dns.org/dns-query
      - tcp-tls:dns-unfiltered.adguard.com
      - https://dns-unfiltered.adguard.com/dns-query
      - tcp-tls:doh.mullvad.net
      - https://doh.mullvad.net/dns-query
      - tcp-tls:dns.switch.ch
      - https://dns.switch.ch/dns-query
      - tcp-tls:dns.dnshome.de
      - https://dns.dnshome.de/dns-query
      - tcp-tls:security-filter-dns.cleanbrowsing.org
      - https://doh.cleanbrowsing.org/doh/security-filter/
      - tcp-tls:dot1.applied-privacy.net
      - https://doh.applied-privacy.net/query
      - tcp-tls:dns.digitale-gesellschaft.ch
      - https://dns.digitale-gesellschaft.ch/dns-query
      - tcp-tls:dns.digitalsize.net
      - https://dns.digitalsize.net/dns-query
      - tcp-tls:unicast.uncensoreddns.org
      - https://unicast.uncensoreddns.org/dns-query
      - tcp-tls:anycast.uncensoreddns.org
      - https://anycast.uncensoreddns.org/dns-query
      - tcp-tls:dot.libredns.gr
      - https://doh.libredns.gr/dns-query
      - tcp-tls:dot.seby.io
      - https://doh.seby.io:8443/dns-query
      - https://doh-2.seby.io/dns-query
      - tcp-tls:getdnsapi.net
      - https://dns.hinet.net/dns-query
      - tcp-tls:ordns.he.net
      - https://ordns.he.net/dns-query
      - tcp-tls:dns.hostux.net
      - https://dns.hostux.net/dns-query
      - tcp-tls:puredns.org
      - https://puredns.org/dns-query
      - tcp-tls:www.morbitzer.de
      - https://www.morbitzer.de/dns-query
      - tcp-tls:ns1.opennameserver.org
      - https://ns1.opennameserver.org/dns-query
      - tcp-tls:ns2.opennameserver.org
      - https://ns2.opennameserver.org/dns-query
      - tcp-tls:ns3.opennameserver.org
      - https://ns3.opennameserver.org/dns-query
      - tcp-tls:ns4.opennameserver.org
      - https://ns4.opennameserver.org/dns-query
      - https://opennic1.eth-services.de:853/
      - https://opennic2.eth-services.de:853/
      - https://pluton.plan9-dns.com/dns-query
      - https://helios.plan9-dns.com/dns-query
      - https://kronos.plan9-dns.com/dns-query
      - https://sby-doh.limotelu.org/dns-query
      - https://chewbacca.meganerd.nl/dns-query
      - https://secure.avastdns.com/dns-query
      - https://dnsnl.alekberg.net/dns-query
      - https://dnsse.alekberg.net/dns-query
      - https://ns1.flodns.net/dns-query
      - https://ns2.flodns.net/dns-query
      - tcp-tls:dns.neutopia.org

caching:
  minTime: 10s
  prefetching: true
  prefetchExpires: 3h
  prefetchThreshold: 100
  prefetchMaxItemsCount: 5000

queryLog:
  logRetentionDays: 7
  creationCooldown: 2s

redis:
  address: 172.17.0.1:6379

ports:
 dns: 53

bootstrapDns:
  - upstream: https://dns.quad9.net/dns-query
    ips:
      - 9.9.9.9
      - 149.112.112.112
  - upstream: https://dns.google/dns-query
    ips:
      - 8.8.8.8
      - 8.8.4.4

connectIPVersion: v4
log:
  level: warn
  format: text
  privacy: true
