---

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.73
    container_name: dnslow.me-adguardhome
    restart: unless-stopped
    healthcheck:
      test: nslookup www.google.com || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
      retries: 1
    ports:
      - "127.0.0.1:3000:3000/tcp"
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      - "853:853/tcp"
      - "853:853/udp"
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
    depends_on:
      - blocky
  blocky:
    image: spx01/blocky:v0.29.0
    container_name: dnslow.me-blocky
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/blocky", "healthcheck"]
      timeout: 5s
      interval: 60s
      start_period: 10s
      retries: 1
    volumes:
      - ./blocky-dns-proxy-config.yml:/app/config.yml
  redis:
    image: redis:8.6-alpine
    container_name: dnslow.me-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "128mb", "--maxmemory-policy", "volatile-lfu"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      interval: 5s
      start_period: 10s
      retries: 3
    volumes:
      - redis-data:/data

volumes:
  redis-data:
