---

version: "2.1"
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.15
    container_name: dnslow.me-adguardhome
    restart: unless-stopped
    healthcheck:
      test: nslookup www.google.com || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
      retries: 1
    ports:
      - "127.0.0.1:3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
    depends_on:
      - blocky
  blocky:
    image: spx01/blocky:v0.19
    container_name: dnslow.me-blocky
    restart: unless-stopped
    healthcheck:
      test: nslookup www.google.com || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
      retries: 1
    volumes:
      - ./blocky-dns-proxy-config.yml:/app/config.yml
